### ISSUE TITLE
How much memory needed for a given size SSD r/w cache

### ISSUE THREAD

**Issue by samuelxhu** [akiradeveloper/dm-writeboost#107]
I am planning to build a 2 nodes Gluster and to use dm-writeboost as read & write cache at the block level to accelerate IOPS. For each 1TB HDD i would like to add an SSD partition of 100GB.

My question is how much memory is needed for each 100GB SSD r/w cache?

AFIK, read cache share the same log segment as write cache except for the dirty flag in metadata. It seems that dm-writeboost destage data from SSD to HDD in a sequential manner, does it mean that the read cache is working in an FIFO mode? Is an LRU mode coming soon for the sake of better read cache performance?

**Comment by akiradeveloper** [comment]
@samuelxhu Hi,

> My question is how much memory is needed for each 100GB SSD r/w cache?

Approximately, 1% of the cache device size is consumed in memory. Therefore, in your case, it would be around 1GB. Paying 1GB of memory to acquire 100GB of SSD cache is cheap or not is up to you.

> AFIK, read cache share the same log segment as write cache except for the dirty flag in metadata.

Exactly. I suppose you have read the code.

> It seems that dm-writeboost destage data from SSD to HDD in a sequential manner, does it mean that the read cache is working in an FIFO mode?

Yes. But precisely, only dirty caches are written back. There is no need to write back clean read caches.

> Is an LRU mode coming soon for the sake of better read cache performance?

umm... unfortunately no. And I don't think it's important because super frequently hit data is likely found in page cache.

**Comment by samuelxhu** [comment]
@akiradeveloper Indeed very interesting software which may find widespread usage. I am seriously considering a r/w ssd cache layer underneath KVM hypervisor, thus LRU cache is not necessary as the virtual machine already has a LRU inside. 

1) May i suppose the code in its current stage production-ready? as I find the Debian officially include it, right? Are your aware of some actual usage in production?

2) need a bit more clarification on writeback_threshold: By setting writeback_threshold=70 it means that the process of writing back from SSD cache to backend HDD will stop if the load of HDD is highly than 70%. I wonder by default writeback_threshold is setting to 0, does it mean the writing back is always prohibited or always ON. In the document a value of zero is "writeback disabled",   I suppose that by default writing back should be switched ON instead of OFF. 

3) For the read cache, there is a parameter "read_cache_threshold" which can skip sequential read requests. For write cache, do you have a plan for a similar write_cache_threshold. My use cases may have tens o HDDs and share one or two SSD write caches (each with multiple partitions). In this case it is more reasonable to let large sequential writes go directly to HDDs, and bypass the SSD write cache. Does it make sense?

**Comment by akiradeveloper** [comment]
@samuelxhu 

> I am seriously considering a r/w ssd cache layer underneath KVM hypervisor, thus LRU cache is not necessary as the virtual machine already has a LRU inside.

That's nice.

1)
> May i suppose the code in its current stage production-ready?

Yes. I think 2.1.2 or later is worth for production.

> as I find the Debian officially include it, right?

Yes. It's a co-work with Dmitry Smirnov, the package maintainer. He also made a nice management tool (https://gitlab.com/onlyjob/writeboost) and this is also found in the Debian repository. 

> Are your aware of some actual usage in production?

No. I know some company engineers have tried out dm-writeboost in their production system but I am not tracking them and not sure they are still using.

2)
> does it mean the writing back is always prohibited or always ON

Prohibited.

> In the document a value of zero is "writeback disabled", I suppose that by default writing back should be switched ON instead of OFF.

In production, there is no need to disable writeback. But I disable it by default because disabling all additional features by default is easy to understand, especially when you write a test. (the code exactly shows what is enabled and otherwise disabled)

3)

> For the read cache, there is a parameter "read_cache_threshold" which can skip sequential read requests. 

Yes. Exactly.

> For write cache, do you have a plan for a similar write_cache_threshold.

No. There is a issue (https://github.com/akiradeveloper/dm-writeboost/issues/66). dm-writeboost is a log-structured caching. If the logs are the history of side-effects without any holes, we can acquire a beautiful nature which is recently included in 2.2.0.

> In this case it is more reasonable to let large sequential writes go directly to HDDs, and bypass the SSD write cache. Does it make sense?

Yes. Because SSD's lifetime is related to the amount of writes. But I think we don't need to care about it at present because enterprise-level SSD has acquired very long lifetime. For performance, bypassing is meaningless and may result in bad performance.

**Comment by samuelxhu** [comment]
@akiradeveloper Got it, no-skipping large sequential writes has its own merit.

Regarding writebacked disabled by default, it makes sense for testing purposes, whereas for real usage there is a high risk that the SSD cache may eventually fill up, thus preventing the block device working properly. Do i understand correctly?

Without writeback function being enabled by default, some people might think the code is still in trial phase.

**Comment by akiradeveloper** [comment]
@samuelxhu 

> Regarding writebacked disabled by default, it makes sense for testing purposes, whereas for real usage there is a high risk that the SSD cache may eventually fill up, thus preventing the block device working properly. Do i understand correctly?

No. block device works correctly even if writeback is disabled. When the SSD is filled up, dm-writeboost tries to write back a segment to make a room for new writes.

If you want to know how it's implemented please search for `urge_writeback` in the source code.

> Without writeback function being enabled by default, some people might think the code is still in trial phase.

There is a related issue (https://github.com/akiradeveloper/dm-writeboost/issues/70)

Dmitry's management tool sets the default value to 70, I suppose. Because I think people shouldn't use dm-writeboost directly but through management tools like Dmirtry's or LVM if possible (it's may be handmade script by the user), I want to make the kernel part neutral.

**Comment by samuelxhu** [comment]
@akiradeveloper Thanks a lot for the clarification. I close this thread as it is not really about a bug.
