### ISSUE TITLE
handling discard requests

### ISSUE THREAD

**Issue by thepax** [akiradeveloper/dm-writeboost#110]
It seems that discard bio is not handled properly. Currently, it's remapped to the backing device immedately. The correct behaviour is to handle it as a write bio, except it has no data. Otherwise, order of bios (discard after write) can be changed. Also read after discard could result in stale data, if it's cached.

**Comment by akiradeveloper** [comment]
@thepax Do you have an actual case that troubles you with discard?

AFAIK, the read data after discard is not defined. Or are you expecting the read data after discard is some particular value such as zero-filled?

**Comment by thepax** [comment]
ATA defines the following TRIM capabilites (see https://en.wikipedia.org/wiki/Trim_%28computing%29 )
- Non-deterministic TRIM: Each read command to the Logical block address (LBA) after a TRIM may return different data.
- Deterministic TRIM (DRAT): All read commands to the LBA after a TRIM shall return the same data, or become determinate.
- Deterministic Read Zero after TRIM (RZAT): All read commands to the LBA after a TRIM shall return zero.

Device examples from https://www.thomas-krenn.com/en/wiki/Ext4_Filesystem 
> [root@fedora15 ~]# hdparm -I /dev/sda | grep 'Model\|TRIM'
> 	Model Number:       OCZ-VERTEX3                             
> 	   *	Data Set Management TRIM supported (limit 1 block)
> 	   *	Deterministic read data after TRIM
> [root@fedora15 ~]# hdparm -I /dev/sdb | grep 'Model\|TRIM'
> 	Model Number:       INTEL SSDSA2CW160G3                     
> 	   *	Data Set Management TRIM supported (limit 8 blocks)
> 	   *	Deterministic read ZEROs after TRIM

Most SAN storages also provide "Deterministic read ZEROs after TRIM", as well as ZFS volumes.

There can be issues with Ext4. It assumes that "any subsequent read after the discard and before write returns zero" (man mkfs.ext4). So it's possible to hit fsck errors just after mkfs on a used write-boosted device.

In any case, since a discard bio can alter data on backing device, it's better to invalidate the cache at least.

Thanks

**Comment by akiradeveloper** [comment]
@thepax Sounds right. But there is one thing I am not sure about is

> In any case, since a discard bio can alter data on backing device, it's better to invalidate the cache at least.

The discard bio now is sent to the designated region of backing device where client claims discardable. So the implementation now doesn't destroy anything important, in other word harmless.

And some possible use-case is using slow SSD as the backing device and the fast SSD as the cache device. In such case, discarding the backing device is necessary to tell the SSD firmware which regions are reclaimable.

Anyway, the result of discard request now is non-deterministic in the terminology and it should be at least deterministic right? If so, I should lookup the cache block when the bio is discard type and redirect the discard bio to the cache block.

**Comment by thepax** [comment]
@akiradeveloper Unfortunately, the current implementation can overwrite discarded blocks by previously cached dirty data. Right? On deterministic backing devices it means 'destroy'. Reading stale data from the cache also 'destroys' deterministically zeroed blocks. This is the issue. 

If you invalidate cache for the discarded region you remove discard deterministicness out of scope. It should work well with any kind of devices. 

If you redirect the discard bio the cache block, you rely on discard deterministicness of the cache device. The cache and the backing device can have different discard determinateness, and things become even more complicated. The worst thing is that the backing device will not receive discard bios. So I think this is not an option.

**Comment by thepax** [comment]
Well. Since there is the issue with deterministic read zeros after discard only, a quick solution is to make the logic configurable. There should be an option to choose the discard bio logic:
1. Process it as is immediately.
2. Convert the discard bio to zero write bio.
3. Cancel the discard bio with EOPNOTSUPP (this should be default).

Furthermore, the second option can be expanded:
2. Put the discard bio into the cache with deterministic read zeros.
2a. Write it to the backing device as zeros.
2b. Issue discard bio to the backing device.

And if you want to go any further, it would be possible to convert a write bio with zeros into the discard bio (configurable option again). This would speedup some workloads.

**Comment by akiradeveloper** [comment]
@thepax 

> Unfortunately, the current implementation can overwrite discarded blocks by previously cached dirty data. Right?

Exactly. Only the region in the backing device is discarded so client read request may hit existing cache. This behavior is not conformant to the deterministic TRIM but only is to the non-deterministic one as you advised me.

I was thinking of how I handle discard requests and I am going to view the writeboost'd device (SSD+HDD) as a HDD that has a huge internal cache. Even the commercial HDDs have internal RAM cache but they are typically MB order. From this point of view, we don't have to care about discard requests because it's just a HDD that discard requests are ignorable. 

If this is correct, it should be ENOTSUPP returned to the client.

If we need to view the writeboost'd device as SSD that discard requests should be handled correctly, possibly in deterministic way, there is a very complicated implementation issue because of partial cache hits; If the request is to discard 4KB region, some sectors may exists in the cache device and others are in the backing device, or it could be in the rambuffer (writeboost has three layers in control).

My conclusion is it's nearly impossible to implement strictly discarding the regions in result of looking up the actual data parts.

And only possible implementation is converting discard bio to zero-filled bio, as in your proposals. But the shortcoming of this idea is realized when the program on top of the writeboost'd device (e.g. filesystem) tries to discard all region of the device before formatting in initialization. This could result in writing back huge amount of (proportional to the backing device size) data from SSD to HDD, which is nearly forever if the backing device is huge.

To tackle this problem, an idea is to convert the discard bio to zero-filled bio but it's marked clean so it doesn't have to be written back. But, this is a trap. If the zeroed data isn't written back, the read data will be changed once the data in the cache is gone when the logging is rotated. Of course, this violates deterministic TRIM.

**Comment by akiradeveloper** [comment]
I found that I set `ti->discard_zeroes_data_unsupported = true;` . This means whether ZRAT (read zero after TRIM) is supported.

**Comment by akiradeveloper** [comment]
and as for discard I should put more settings

this is from dm-cache-target.c

```c
	ti->num_discard_bios = 1;
	ti->discards_supported = true;
	ti->discard_zeroes_data_unsupported = true;
	ti->split_discard_bios = false;
```

and mine

```c
	ti->num_discard_bios = 1;
	ti->discard_zeroes_data_unsupported = true;
```

I should also reconsider the settings.
