### ISSUE TITLE
Need help with creating a ram block device.

### ISSUE THREAD

**Issue by joeey1984ad** [akiradeveloper/dm-writeboost#142]
@akiradeveloper 

Thanks for clarifying the last issue. I have a question regarding building the writeboost cache with a ram block device instead of SSD. however when I create the writeboost device with ram block, the performance is very poor. I wanted to know if the steps I am making in terms of creating ram device is correct? 

1. /bin/dd if=/dev/zero of=/tmp/ramloop0 bs=333048576 count=4096
2. /sbin/losetup -v /dev/loop0 /tmp/ramloop0
3. chown root:disk /dev/loop0 
4. sudo dmsetup create mylv --table "0 `blockdev --getsize /dev/md0` writeboost /dev/md0 /dev/loop0"
5. mkfs.ext4   /dev/mapper/mylv
6. mount /dev/mapper/mylv /home

**Comment by akiradeveloper** [comment]
@joeey1984ad 

I have several tests that uses memory device which is created in the same way. I think the way you creates a memory device is correct.

From my past experiments, with the memory device writeboost can achieve 1.5GB/s random 4KB writes. This is crazy fast.

> /bin/dd if=/dev/zero of=/tmp/ramloop0 bs=333048576 count=4096

How big the memory you have in your system? 333MB * 4096 is more than 1TB. In my understanding is correct, /tmp is tmpfs and tmpfs is memory filesystem backed by the backing filesystem. So if you don't have 1TB memory, most of the data locates in the filesystem.

but in the first place I want to advise you, it's not technical, if you say something's performance is poor you should share the evidence. In this case, you should share the throughput value and sysstat snapshot. complaining without evidence sounds unfair to me.

**Comment by joeey1984ad** [comment]
Hi, thanks for your response. I will share a fio test and a sysbench test, both from "SSD write boost device" and "Ram Disk Writeboost" soon. I am sure something is wrong in terms of me creating the ram disk. I used "bs=333048576" just to make sure I get as much RAM as possible.
The outcome of the dd is given below. The system allocates 16GB ram disk.
 
"/bin/dd if=/dev/zero of=/tmp/ramloop0 bs=333048576 count=4096"

/bin/dd: error writing ‘/tmp/ramloop0’: No space left on device

19112038400 bytes (19 GB) copied, 13.6389 s, 1.4 GB/s

**Comment by akiradeveloper** [comment]
@joeey1984ad If the ramdisk is 16GB the caching device immediately becomes full (no empty room to write) within 10 seconds. Without writing back filled segments, writeboost can't write anymore. In this scenario, the write throughput is almost peaked by the speed of writing backing to backing store. It may be less than 10MB/s.

But it's still better than not using writeboost and directly writing to the backing store because writeboost's highly optimized in the writeback algorithm. Which is called "batched writeback".

**Comment by akiradeveloper** [comment]
There is a recommendation by Dmitry to use ramdisk as the caching device

https://github.com/lizardfs/lizardfs/issues/286

> IMHO dm-writeboost is also great with RAM disks as caching devices.

**Comment by joeey1984ad** [comment]
What is the recommended Ram Disk  for 1.5 TB DATA on writeboost?

**Comment by akiradeveloper** [comment]
@joeey1984ad I don't know because it depends on the use case but I recommend you to use writeboost with SSD in production. It's designed to be used with SSD

**Comment by joeey1984ad** [comment]
Can I use two SSD without RAID1, because on raid1 I lose some speed !? For example can I setup writeboost so that each 2x480GB stores identical data but not on RAID1?

**Comment by akiradeveloper** [comment]
@joeey1984ad No. only one caching device and only one backing store. There is no option to use multiple caching devices. If you want to cache identical data on the two SSDs, you can use RAID0.

In case caching device is broken, thanks to the log-structured nature, the storage loses dirty cached data **strictly from** the newer ones. In other words, the state of storage is back to some point in the past like snapshot. So the database or filesystem may be able to stay sane. But only the data is bit old.

With this property we can say writeboost is safer than other caching drivers because other drivers can't have this property. Usually, important storage data is backed up to other low cost servers. And in case of trouble, the storage is recovered using these backups. Getting back to the older state is truly same as this operation so this property is very useful in production.

**Comment by joeey1984ad** [comment]
Wow, this is a great feature, As far as LVMcache goes if the SSD device which is the caching device gets destroyed your data also gets destroyed. 
P.S Are you sure about RAID0 having identical DATA on two disks. I thought RAID0 splits data half and half?

**Comment by pttpzp** [comment]
@joeey1984ad  RAID0 is not safe

**Comment by akiradeveloper** [comment]
@joeey1984ad 

> Are you sure about RAID0 having identical DATA on two disks

Yes.

And if the storage is allowed to go back to the older state in case caching device is broken, as I explained, 

> In case caching device is broken, thanks to the log-structured nature, the storage loses dirty cached data strictly from the newer ones. In other words, the state of storage is back to some point in the past like snapshot. So the database or filesystem may be able to stay sane. But only the data is bit old.

RAID0 is considerable.

However, I don't truly recommend it because, as @pttpzp says, using RAID0 reduces the MTTF.

Since SSD is much faster than HDD RAID, there is no reason to build RAID0 of SSDs in terms of performance, risking the failure. If your concern is the capacity utilization that RAID1 sacrifies, I recommend you to buy a single larger SSD.

**Comment by joeey1984ad** [comment]
Perfect, it makes sense.
 One last question. As you mentioned if the SSD caching device fails the HDD goes back to snapshot and loses some dirty blocks. Imagine such a case happens and I want to add a new SSD cache device to the old HDD containing the DATA. Is writeboost able to be created to a HDD that already has the old DATA. 
One of the steps is, 'mkfs.ext4 -b 4096 /dev/mapper/mylv'. Wouldn't that destroy the whole data. Can the /dev/mapper/mylv be mounted without mkfs?

**Comment by akiradeveloper** [comment]
@joeey1984ad 

> Is writeboost able to be created to a HDD that already has the old DATA. 

Yes.

> One of the steps in making writeboost is, 'mkfs.ext4 -b 4096 /dev/mapper/mylv'. Wouldn't that destroy the whole data. 

Don't mkfs again.

> Can the /dev/mapper/mylv be mounted without mkfs?

Yes.

**Comment by joeey1984ad** [comment]
Thank you. I will leave this issue as closed.

**Comment by onlyjob** [comment]
> There is a recommendation by Dmitry to use ramdisk as the caching device

I do not recommend to use ramloop devices on _tmpfs_.
Instead one can use a proper RAM _block_ device with __brd__ kernel module:

~~~~
/sbin/modprobe -v brd rd_nr=7 rd_size=102400
/bin/dd if=/dev/zero of=/dev/ram0 count=1
~~~~

See more in https://kernel.org/doc/Documentation/blockdev/ramdisk.txt

**Comment by akiradeveloper** [comment]
@onlyjob oh this is great. I want to implement tests using brd in writeboost-test-suite.

btw, the ram0 should be ram7 because rd_nr is 7?

```
2b) Module parameters

	rd_nr
	=====
	/dev/ramX devices created.
```

**Comment by onlyjob** [comment]
`rd_nr` controls number of devices. I usually set `rd_nr>1` in case I need more than one device. `ram0` is a first device (enumerated from zero) and with `rd_nr=7` the last device would be `ram6` (`ram7` do not exist as it would be 8th device).
