### ISSUE TITLE
ioprio hinting to bypass cache (or writeback cache)

### ISSUE THREAD

**Issue by marcin-github** [akiradeveloper/dm-writeboost#174]
Hi!
I' dont know if you are aware of this thread [http://www.spinics.net/lists/linux-bcache/msg04214.html](http://www.spinics.net/lists/linux-bcache/msg04214.html) . Would it be hard to add similar feature to dm-writeboost?

**Comment by akiradeveloper** [comment]
No.

Again, writeboost can't bypass writes. Bypassing writes would result to destructing the consistency when the caching device dies. It's not about implementation difficulty but correctness. I think bcache sacrifices the property that consistency is maintained after caching device corruption and it's only tradeoff. It's just I am going the different way.

It's also important for writeboost to go the other ways than other caching solutions. Otherwise, writeboost will be just crap. That writeboost can attract some attention is just because it's unlike bcache or dm-cache. Making bcache-like something again is completely meaningless.

Only features that naturally adaptable to writeboost's concept and architecture will be implemented.

But yeah, thanks for notifying me the bcache's feature that I didn't know.

**Comment by marcin-github** [comment]
Ah, yeah, it was obvious, writeboost keeps order of writed blocks. Thanks for quick reply!

**Comment by akiradeveloper** [comment]
> writeboost keeps order of writed blocks

exactly
