### ISSUE TITLE
not a big performance impact

### ISSUE THREAD

**Issue by pipes80-collab** [akiradeveloper/dm-writeboost#230]
it does not have a significant impact on performance, maybe I will have set something wrong but I doubt
Disable
![dm-writeboost_disable](https://user-images.githubusercontent.com/56699284/131737034-d394429f-f07d-4bdd-9f65-4b87489cebfd.png)
Enable
![dm-writeboost_enable](https://user-images.githubusercontent.com/56699284/131737037-c5d49a18-5cd5-473c-bc35-dfddc38539ca.png)

**Comment by akiradeveloper** [comment]
Hi @pipes80-collab,

Can you describe what you did? I have completely no clue with these two figures.

**Comment by pipes80-collab** [comment]
I use the sale command into the video

**Comment by akiradeveloper** [comment]
Sorry, I can't help you.

You need to share 

- Kernel version, writeboost version
- What devices you use
- state of lsblk
- etc

to ask me for help.

But let's make a guess: Since the two figures show almost the same result, I bet you don't use writeboost at all. In addition, since the throughput is too high I guess you are trying to use solid drive as the backing storage, which isn't the usage of writeboost.

**Comment by pipes80-collab** [comment]
Wait and i telo all information
