### ISSUE TITLE
Feature: bypass cache on sequential I/O

### ISSUE THREAD

**Issue by disaster123** [akiradeveloper/dm-writeboost#66]
It would be great to be able to bypass the cache when we have sequential I/O.

**Comment by akiradeveloper** [comment]
Basically, I consider bypassing the sequential write is dangerous for caching softwares.

"All side effects once go through the cache device in logging manner" is a beautiful principle that dm-writeboost implements.

Let's consider that your cache device suddenly corrupts - we can't neither write nor read, but you need to mount with only the backing store. If side-effects once bypassed the cache device, the filesystem in the backing store may be broken. In other word, what's in the cache device is always newer than what's in the backing store can give us higher level of robustness. Note that dm-writeboost writes back data from older segments.

So, it's possible but I don't like to implement because what dm-writeboost sells is _not_ the performance but the robustness.

**Comment by disaster123** [comment]
OK makes sense
